%% New code, checking some of that output format
% All of the ones from March 10, 2023.
files = [
         "Data/Water100pc-Test1-Exp022.txt", ...
         "Data/Water100pc-Test2-Exp023.txt", ...
         "Data/Water100pc-Test3-Exp024.txt", ...
         "Data/Water100pc-Test4-Exp025.txt", ...
         "Data/Water100pc-Trial1-Exp026.txt", ...
         "Data/Water100pc-Trial2-Exp027.txt", ...
         "Data/Water100pc-Trial3-Exp028.txt", ...
         "Data/Ethanol5pc-Test-Exp029.txt", ...
         "Data/Ethanol5pc-Trial1-Exp030.txt", ...
         "Data/Ethanol5pc-Trial2-Exp031.txt", ...
         "Data/Ethanol5pc-Trial3-Exp032.txt", ...
         "Data/Ethanol10pc-Test1-Exp033.txt", ...
         "Data/Ethanol10pc-Test2-Exp034.txt", ...
         "Data/Ethanol10pc-Test3-Exp035.txt", ...
         "Data/Ethanol10pc-Trial1-Exp036.txt", ...
         "Data/Ethanol10pc-Trial2-Exp037.txt", ...
         "Data/Ethanol10pc-Trial3-Exp038.txt", ...
         "Data/Ethanol25pc-Trial1-Exp039.txt"
         ];
filenicknames = [
                "100% Water Test 1", "100% Water Test 2", "100% Water Test 3", "100% Water Test 4", ...
                "100% Water Trial 1", "100% Water Trial 2", "100% Water Trial 3",...
                "5% Ethanol Test", ...
                "5% Ethanol Trial 1", "5% Ethanol Trial 2", "5% Ethanol Trial 3", ...
                "10% Ethanol Test 1", "10% Ethanol Test 2", "10% Ethanol Test 3", ...
                "10% Ethanol Trial 1", "10% Ethanol Trial 2", "10% Ethanol Trial 3", ...
                "25% Ethanol Trial 1"
                ];
fileparameters = [
                  0, 0, 0, 0, ...
                  0, 0, 0, ...
                  5, 5, 5, 5, ...
                  10, 10, 10, 10, 10, 10, ...
                  25
                  ];

test = ParticleSizeAnalysis(files, filenicknames, fileparameters, 1, 100, 0, 100, 4, 5);

ethanoltest = SAWDataComparison(files, filenicknames, fileparameters, 100, 0, 100, 4, 5)
% Change graph name to be about the range, not "100 um and below"
% Will need to rewrite my code to accomodate having better data. Maybe
% instead have it be snapshots records like from the spraytec software? Or
% just average everything out.
% 
ethanoltest.getRFGraph();
ethanoltest.getFPFGraph();
ethanoltest.getMMADGraph();
ethanoltest.AnalyseDistribution();
ethanoltest.AnalyseNebVarsSnapshots();


%% Old code
% files = ["TestData/10E-Exp33.txt","TestData/10E-Trial1-Exp36.txt","TestData/10E-Trial3-Exp38.txt","TestData/5E-Trial1-Exp30.txt","TestData/5E-Trial2-Exp31.txt","TestData/5E-Trial3-Exp32.txt","TestData/W-Trial1-Exp26.txt","TestData/W-Trial2-Exp27.txt","TestData/W-Trial3-Exp28.txt"];
% files = fliplr(files);
% filenicknames = ["10% Ethanol Exp1","10% Ethanol Exp2","10% Ethanol Exp3","5% Ethanol Exp1","5% Ethanol Exp2","5% Ethanol Exp3", "Water Exp1", "Water Exp2", "Water Exp3"];
% filenicknames = fliplr(filenicknames);
% fileparameters = [10,10,10,5,5,5,0,0,0];
% fileparameters = fliplr(fileparameters);
% maximumcutoffdiameter = 100;
% minzoomdiameter = 0;
% maxzoomdiameter = 100;
% rfthreshold = 4;
% fpfthreshold = 5;
% 
% ethanoltest1 = SAWDataComparison(files,filenicknames, fileparameters, maximumcutoffdiameter, minzoomdiameter, maxzoomdiameter, rfthreshold, fpfthreshold)
% ethanoltest1.getRFGraph();
% ethanoltest1.getFPFGraph();
% ethanoltest1.getMMADGraph();
% ethanoltest1.AnalyseNebVarsSnapshots();
% ethanoltest1.AnalyseDistribution();